### PR TITLE
Fix error in travelplan edit page

### PR DESCRIPTION
**Pull request by jeffwang0516**
Error 500 fixed:
Error raises when one station exists in multiple travelplans.

### CODE REVIEW

**Comment by rapirent** [comment]
Got it.
Then but why the for loop should have remained?

**Comment by jeffwang0516** [comment]
Because it's removing TravelPlanStations entries for the travelplan & station ids  in the array.
Ex. 
travelplan   station
1                  23
1                  32
1                  33
3                  44
.
.
.
How would you fix ?

**Comment by rapirent** [comment]
Okay, I just misunderstood.
That makes sense.

**Comment by rapirent** [comment]
LGTM, merged.

**Pull request merged**
